version : '3'

services :
        mysql : 
                image : 'mysql:latest'
                restart : always
                environment :
                        MYSQL_ROOT_PASSWORD: es
                        MYSQL_DATABASE : database
                        MYSQL_USER: User
                        MYSQL_PASSWORD: es
                networks :
                        global_network : 
                                ipv4_address : 172.16.238.1
                ports : 
                        - "3306:3306"
                logging :
                        driver : gelf
                        options :
                                tag : "SoftwareEngineeringDB"
        tomcat :
                image : tomcat
                restart : always
                networks : 
                        global_network :
                                ipv4_address : 172.16.238.2
                ports : 
                        - "8080:8080"
                environment : 
                logging :
                        driver : gelf
                        options :
                                tag : "MainProject"


networks:
        global_network:
                driver : bridge
                ipam : 
                        driver : default
                        config : 
                                - subnet : 172.16.238.0/24
