version : '3'

services :
        mysql :
                container_name : MySQL 
                image : 'mysql:latest'
                restart : always
                environment :
                        MYSQL_ROOT_PASSWORD: es
                        MYSQL_DATABASE : database
                        MYSQL_USER: User
                        MYSQL_PASSWORD: es
                networks :
                        global_network : 
                                ipv4_address : 172.16.238.10
                ports : 
                        - "3306:3306"
        main :
                container_name : MainProgram   
                build:
                    context: ./MainProject/dockerdemo
                    dockerfile: DockerFile
                restart : always
                networks : 
                        global_network :
                                ipv4_address : 172.16.238.20
                ports : 
                        - "8080:8080"  
                depends_on :
                    - mysql
                    - elasticsearch
        dashboard :
                container_name : Dashboard     
                build:
                        context: ./Dashboard/interface
                        dockerfile: Dockerfile
                volumes:
                        - './Dashboard/interface:/usr/src/app'
                        - '/usr/src/app/node_modules'
                networks:
                        global_network:
                                ipv4_address: 172.16.238.40
                ports:
                        - '3001:3001'
                environment:
                        - NODE_ENV=development
                depends_on:
                        - main
        elasticsearch:
                container_name : Elastic_Search
                build:
                        context: elasticsearch/
                volumes:
                        - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
                ports:
                        - "9200:9200"
                        - "9300:9300"
                networks:
                        global_network:
                                ipv4_address: 172.16.238.60
        grafana :
                image : 'grafana/grafana:latest'
                container_name : Grafana
                volumes :
                        - './grafana/config/:/usr/share/grafana/config:ro'
                ports :
                        - "3000:3000"
                networks :
                        global_network :
                                ipv4_address : 172.16.238.50
                environment:
                        - GF_SERVER_ROOT_URL=http://projectES.com:3000/
                        - GF_SECURITY_ADMIN_USER=User
                        - GF_SECURITY_ADMIN_PASSWORD=enterro2019
                        - GF_SMTP_ENABLED=true
                        - GF_SMTP_HOST=smtp.gmail.com:587
                        - GF_SMTP_USER=grafana@example.com
                        - GF_SMTP_FROM_ADDRESS=grafana@example.com
                        - GF_SMTP_PASSWORD=******
                        - GF_USERS_ALLOW_SIGN_UP=false
                        - GF_ALERTING_ERROR_OR_TIMEOUT=keep_state
                restart: always                
                depends_on :
                        - elasticsearch                                       
networks:
        global_network:
                driver : bridge
                ipam : 
                        driver : default
                        config : 
                                - subnet : 172.16.238.0/24
