version : '3'

services :
        mysql : 
                image : 'mysql:latest'
                restart : always
                environment :
                        MYSQL_ROOT_PASSWORD: es
                        MYSQL_DATABASE : database
                        MYSQL_USER: User
                        MYSQL_PASSWORD: es
                networks :
                        global_network : 
                                ipv4_address : 172.16.238.10
                ports : 
                        - "3306:3306"
        main :
                build:
                    context: ./MainProject/dockerdemo
                    dockerfile: DockerFile
                restart : always
                networks : 
                        global_network :
                                ipv4_address : 172.16.238.20
                ports : 
                        - "8080:8080"  
                depends_on :
                    - mysql
        dashboard :
                build:
                        context: ./Dashboard/interface
                        dockerfile: Dockerfile
                volumes:
                        - './Dashboard/interface:/usr/src/app'
                        - '/usr/src/app/node_modules'
                networks:
                        global_network:
                                ipv4_address: 172.16.238.40
                ports:
                        - '3000:3000'
                environment:
                        - NODE_ENV=development
                depends_on:
                        - main

networks:
        global_network:
                driver : bridge
                ipam : 
                        driver : default
                        config : 
                                - subnet : 172.16.238.0/24
