source "http://rubygems.org"
source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "jekyll", "3.5.0"

# If you have any plugins, put them here!
group :jekyll_plugins do
    #gem "minimal-mistakes-jekyll"
    gem "jekyll-sitemap"
    gem "sass"
end
