pipeline {
    agent any
    stages {
        stage('Cloning repository') {
            steps {
                git(
                    branch: 'master',
                    credentialsId: 'c1b055da-53b9-4c9d-8d7b-e9165d36af5c',
                    url: 'https://github.com/DanMartyns/SoftwareEngineering.git'
                )
            }
        }
        stage ('Build') {
            steps {
                echo 'Building'
                sh 'mvn -f P2G1/MainProject/dockerdemo/pom.xml -Dmaven.test.failure.ignore=false package'
            }
        }
        stage('Build (without tests)') {
            steps {
                sh './P2G1/Jenkins/scripts/build_without_tests.sh'
            }
        }
        
        stage('Build (with tests)') {
            steps {
                // Build will stop if one of the tests went wrong
                echo 'Build will stop if one of the tests went wrong'
                sh './P2G1/Jenkins/scripts/build_with_tests.sh'
            }
        }
        stage ('Deploy') {
            steps{
                echo 'Deploying'
                sh "wget '192.168.160.80:20401' > /dev/null 2>&1 &"

            }   
        }
    }
} 
