FROM java:8
EXPOSE 42020 42020
COPY /src/main/resources/mysql-connector-java-8.0.16.jar mysql-connector-java-8.0.16.jar
ADD /target/MainProgram.jar MainProgram.jar
ENTRYPOINT ["java","-classpath","/home/danielmartins/Documentos/Universidade/ES/Project/SoftwareEngineering/MainProject/dockerdemo/src/main/resources/mysql-connector-java-8.0.16.jar:.", "-jar", "MainProgram.jar"]
