pipeline {
    agent any
    stages {
        stage('Cloning repository') {
            steps {
                git(
                    branch: 'master',
                    credentialsId: 'c1b055da-53b9-4c9d-8d7b-e9165d36af5c',
                    url: 'https://github.com/DanMartyns/SoftwareEngineering.git'
                )
            }
        }
    }
}
