title: ECGMonitor
email: danielmcoelho@ua.pt
description: >
    The tool to monitor the ECG.
owner_name: HeartRate Monitor
owner_url: https://danmartyns.github.io/SoftwareEngineering/
repository_name: SoftwareEngineering
repository_url: https://danmartyns.github.io/SoftwareEngineering
github_username:  danmartyns

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: ""
#baseurl: "https://danmartyns.github.io/SoftwareEngineering/docs"
show_dir_listing: false

show_full_navigation: true

gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
